"""The formatter contract — generated bytes must be canonical for the pinned oxfmt.

Regression: `package.json` declared `"oxfmt": ">=0.15"`, nothing shipped a lockfile, and the
generated CI gate is `pnpm run format` -> `oxfmt --check .`. So a generated repo resolved a
formatter newer than the bytes were authored for and went red on its first push — 0.15.0 left
the tree untouched, 0.17.0 rewrote seven files. Worse, `--update` put the non-canonical bytes
back, so a local `pnpm run format:fix` never stuck.

The generator now canonicalizes at its single write seam (see the formatter contract block in
scaffold.py), and these tests are the gate that keeps the pin and the bytes in step: bump
OXFMT_VERSION, watch the last test reformat, commit what it changes.
"""

import importlib.util
import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

SKILL_DIR = Path(__file__).resolve().parent.parent.parent / "skills" / "scaffold"
SCRIPT = SKILL_DIR / "scripts" / "scaffold.py"


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


scaffold = _load("scaffold_mod_oxfmt_contract", SCRIPT)


# --- the pin ----------------------------------------------------------------


def test_oxfmt_dependency_is_pinned_exactly():
    """A range is what let CI resolve a formatter that disagrees with the shipped bytes."""
    pkg = json.loads(scaffold.build_package_json("demo", "lib", with_coverage=False))
    assert pkg["devDependencies"]["oxfmt"] == scaffold.OXFMT_VERSION
    assert scaffold.OXFMT_VERSION[0].isdigit(), "pin must be an exact version, not a range"


# --- the seam is inert unless a TypeScript flavor enables it ------------------


def test_canonicalize_is_inert_until_the_run_enables_it():
    """`main()` enables the formatter for every flavor; until it does, the seam is a no-op, which
    is what lets the module be imported and unit-tested without Node."""
    path = Path("notes.md")
    assert scaffold.canonicalize(path, "# H\ntext\n") == "# H\ntext\n"


def test_unsupported_extensions_are_never_piped_to_the_formatter(monkeypatch, tmp_path):
    """oxfmt exits 1 with "Unsupported file type" on `.py`/`.sh`; the allowlist keeps them out."""
    monkeypatch.setattr(scaffold, "_formatter_root", tmp_path)
    assert scaffold.canonicalize(tmp_path / "x.py", "x = 1\n") == "x = 1\n"
    assert scaffold.canonicalize(tmp_path / "x.sh", "echo 1\n") == "echo 1\n"


# --- the gate the generated CI runs -----------------------------------------


def _scaffold(cwd: Path, *args: str) -> None:
    subprocess.run(
        [sys.executable, str(SCRIPT), *args, "--project-name", "demo", "--cwd", str(cwd)],
        check=True,
        capture_output=True,
        text=True,
    )


@pytest.mark.skipif(shutil.which("npx") is None, reason="needs Node/npx to run the pinned oxfmt")
@pytest.mark.parametrize(
    "sequence",
    [
        pytest.param([["--flavor", "git"], ["--flavor", "typescript"]], id="git-then-typescript"),
        pytest.param(
            [["--flavor", "git"], ["--flavor", "ci", "--ci-variant", "node"]],
            id="git-then-ci-node",
        ),
        pytest.param(
            [["--flavor", "python", "--with-coverage"], ["--flavor", "typescript"]],
            id="python-then-typescript",
        ),
        pytest.param(
            [["--flavor", "rust", "--with-coverage"], ["--flavor", "typescript"]],
            id="rust-then-typescript",
        ),
        pytest.param(
            [["--flavor", "typescript"], ["--flavor", "ci", "--ci-variant", "node"]],
            id="typescript-then-ci-node",
        ),
        pytest.param(
            [["--flavor", "ci", "--ci-variant", "node"], ["--flavor", "typescript"]],
            id="ci-node-then-typescript",
        ),
        pytest.param(
            [["--flavor", "all"], ["--update", "--flavor", "git"]], id="refresh-git-after-all"
        ),
        pytest.param(
            [["--flavor", "all"], ["--update", "--flavor", "ci"]], id="refresh-ci-after-all"
        ),
    ],
)
def test_an_invocation_split_never_changes_the_bytes(monkeypatch, tmp_path, sequence):
    """oxfmt's reach spans files several flavors own, so the bytes must not depend on how the run
    was split. Reproduced before the fix: `--flavor all` then `--update --flavor git` left
    `.releaserc.json` uncanonical, and `--flavor typescript` then `--flavor ci --ci-variant node`
    left `release.yml` uncanonical — neither run had the formatter enabled, so the generated
    `pnpm run format` gate went red on bytes no gate had judged. The check runs after *every*
    invocation, so a flavor that emits uncanonical bytes is caught as the writer, not later."""
    monkeypatch.delenv("SCAFFOLD_NO_FORMAT", raising=False)
    for args in sequence:
        _scaffold(tmp_path, *args)
        if not (tmp_path / ".oxfmtrc.json").exists():
            # No formatter config in the tree means no `pnpm run format` gate to satisfy yet.
            continue
        gate = subprocess.run(
            ["npx", "--yes", f"oxfmt@{scaffold.OXFMT_VERSION}", "--check", "."],
            cwd=str(tmp_path),
            capture_output=True,
            text=True,
        )
        assert gate.returncode == 0, f"after {' '.join(args)}\n{gate.stdout}{gate.stderr}"


@pytest.mark.skipif(shutil.which("npx") is None, reason="needs Node/npx to run the pinned oxfmt")
def test_generated_tree_passes_its_own_ci_format_gate(monkeypatch, tmp_path):
    """Generate with the formatter live, then run exactly what the generated `verify` job runs."""
    monkeypatch.delenv("SCAFFOLD_NO_FORMAT", raising=False)
    subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--flavor",
            "all",
            "--project-name",
            "demo",
            "--ts-variant",
            "lib",
            "--cwd",
            str(tmp_path),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    gate = subprocess.run(
        ["npx", "--yes", f"oxfmt@{scaffold.OXFMT_VERSION}", "--check", "."],
        cwd=str(tmp_path),
        capture_output=True,
        text=True,
    )
    assert gate.returncode == 0, gate.stdout + gate.stderr
