"""The formatter contract — generated bytes must be canonical for the pinned oxfmt.

Regression: `package.json` declared `"oxfmt": ">=0.15"`, nothing shipped a lockfile, and the
generated CI gate is `pnpm run format` -> `oxfmt --check .`. So a generated repo resolved a
formatter newer than the bytes were authored for and went red on its first push — 0.15.0 left
the tree untouched, 0.17.0 rewrote seven files. Worse, `--update` put the non-canonical bytes
back, so a local `pnpm run format:fix` never stuck.

The generator now canonicalizes at its single write seam (see the formatter contract block in
scaffold.py), and these tests are the gate that keeps the pin and the bytes in step: bump
OXFMT_VERSION, watch the last test reformat, commit what it changes.
"""

import importlib.util
import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

SKILL_DIR = Path(__file__).resolve().parent.parent.parent / "skills" / "scaffold"
SCRIPT = SKILL_DIR / "scripts" / "scaffold.py"


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


scaffold = _load("scaffold_mod_oxfmt_contract", SCRIPT)


# --- the pin ----------------------------------------------------------------


def test_oxfmt_dependency_is_pinned_exactly():
    """A range is what let CI resolve a formatter that disagrees with the shipped bytes."""
    pkg = json.loads(scaffold.build_package_json("demo", "lib", with_coverage=False))
    assert pkg["devDependencies"]["oxfmt"] == scaffold.OXFMT_VERSION
    assert scaffold.OXFMT_VERSION[0].isdigit(), "pin must be an exact version, not a range"


# --- the seam is inert unless a TypeScript flavor enables it ------------------


def test_formatter_is_off_until_enabled():
    """git/python/rust runs stay pure Python: no Node, no formatter, no config to satisfy."""
    path = Path("notes.md")
    assert scaffold.canonicalize(path, "# H\ntext\n") == "# H\ntext\n"


def test_unsupported_extensions_are_never_piped_to_the_formatter(monkeypatch, tmp_path):
    """oxfmt exits 1 with "Unsupported file type" on `.py`/`.sh`; the allowlist keeps them out."""
    monkeypatch.setattr(scaffold, "_FORMATTER_ROOT", tmp_path)
    assert scaffold.canonicalize(tmp_path / "x.py", "x = 1\n") == "x = 1\n"
    assert scaffold.canonicalize(tmp_path / "x.sh", "echo 1\n") == "echo 1\n"


# --- the gate the generated CI runs -----------------------------------------


@pytest.mark.skipif(shutil.which("npx") is None, reason="needs Node/npx to run the pinned oxfmt")
def test_generated_tree_passes_its_own_ci_format_gate(monkeypatch, tmp_path):
    """Generate with the formatter live, then run exactly what the generated `verify` job runs."""
    monkeypatch.delenv("SCAFFOLD_NO_FORMAT", raising=False)
    subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--flavor",
            "all",
            "--project-name",
            "demo",
            "--ts-variant",
            "lib",
            "--cwd",
            str(tmp_path),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    gate = subprocess.run(
        ["npx", "--yes", f"oxfmt@{scaffold.OXFMT_VERSION}", "--check", "."],
        cwd=str(tmp_path),
        capture_output=True,
        text=True,
    )
    assert gate.returncode == 0, gate.stdout + gate.stderr
