#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///

"""
Deterministic scaffold generator — tool owns bytes, model owns intent.

Usage:
  uv run $SKILL_DIR/scripts/scaffold.py --flavor git [--project-name NAME] [--dry-run]
  uv run $SKILL_DIR/scripts/scaffold.py --flavor python [--project-name NAME] [--dry-run] [--with-coverage --coverage-threshold 80]
  uv run $SKILL_DIR/scripts/scaffold.py --flavor rust [--project-name NAME] [--dry-run] [--with-coverage --coverage-threshold 80]
  uv run $SKILL_DIR/scripts/scaffold.py --flavor ci [--project-name NAME] [--dry-run] [--with-coverage]
  uv run $SKILL_DIR/scripts/scaffold.py --flavor all [--project-name NAME] [--dry-run] [--with-coverage]

Information boundary: script emits byte-identical artifacts; for mixed
deterministic+semantic files it writes the skeleton and warns on stderr
so the model proofreads semantic sections. Never hand-copy templates.
This script is the single source of truth — preview with --dry-run.
"""

from __future__ import annotations

import argparse
import difflib
import pathlib
import sys

# ------------------------------------------------------------------ templates (pure-deterministic except {{project_name}})
RELEASERC_JSON = """\
{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    [
      "@semantic-release/release-notes-generator",
      {
        "preset": "conventionalcommits",
        "presetConfig": {
          "types": [
            {"type": "feat", "section": "Features"},
            {"type": "fix", "section": "Bug Fixes"},
            {"type": "perf", "section": "Performance Improvements"},
            {"type": "revert", "section": "Reverts"},
            {"type": "docs", "section": "Documentation", "hidden": false},
            {"type": "style", "section": "Styles", "hidden": true},
            {"type": "chore", "section": "Miscellaneous Chores", "hidden": true},
            {"type": "refactor", "section": "Code Refactoring", "hidden": true},
            {"type": "test", "section": "Tests", "hidden": true},
            {"type": "build", "section": "Build System", "hidden": true},
            {"type": "ci", "section": "Continuous Integration", "hidden": true}
          ]
        }
      }
    ],
    ["@semantic-release/changelog", {"changelogFile": "CHANGELOG.md"}],
    "@semantic-release/github",
    [
      "@semantic-release/git",
      {
        "assets": ["CHANGELOG.md", "package.json", "package-lock.json"],
        "message": "chore(release): ${nextRelease.version} [skip ci]\\n\\n${nextRelease.notes}"
      }
    ]
  ]
}
"""

RELEASE_YML = """\
name: Verify and Release
on:
  repository_dispatch:
    types: [semantic-release]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with: {fetch-depth: 0}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4  # zizmor: ignore[cache-poisoning]
        with: {node-version: 22}
      - run: npm ci
      - run: npm audit signatures
      - run: npm test
  release:
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with: {fetch-depth: 0}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4  # zizmor: ignore[cache-poisoning]
        with: {node-version: 22}
      - run: npm ci
      - run: npm audit signatures
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
"""

COMMITLINT_JS = 'export default { extends: ["@commitlint/config-conventional"] };\n'

CONTRIBUTING_MD_TMPL = """\
# Contributing to {project_name}
## Conventional commits
- `feat[(scope)]: description` → MINOR, `fix[(scope)]:` → PATCH, `feat!:` / `BREAKING CHANGE:` → MAJOR
- Other types `docs|style|refactor|perf|test|build|ci|chore|revert` hidden unless `!`
- Scope is noun, description imperative present, lowercase, no period, ≤72 chars
- Enforced by `commitlint` + `husky` (`npx commitlint --from=origin/main --to=HEAD`)
## Changelog
Do not edit `CHANGELOG.md`. Changelog is generated by `semantic-release` on `repository_dispatch` (`gh api repos/.../dispatches -f event_type=semantic-release`) or `workflow_dispatch` — no manual `git tag`.
## Before PR
`npm run lint && npm run typecheck && npm test` must pass. See `AGENTS.md` for agent rules.
"""

CONTRIBUTING_MD_TMPL_PYTHON = """\
# Contributing to {project_name}
## Conventional commits
- `feat[(scope)]: description` → MINOR, `fix[(scope)]:` → PATCH, `feat!:` / `BREAKING CHANGE:` → MAJOR
- Other types `docs|style|refactor|perf|test|build|ci|chore|revert` hidden unless `!`
- Scope is noun, description imperative present, lowercase, no period, ≤72 chars
- Enforced by `commitlint` + `husky` (`npx commitlint --from=origin/main --to=HEAD`)
## Changelog
Do not edit `CHANGELOG.md`. Changelog is generated by `semantic-release` on `repository_dispatch` (`gh api repos/.../dispatches -f event_type=semantic-release`) or `workflow_dispatch` — no manual `git tag`.
## Before PR
`uv run ruff check . && uv run basedpyright && uv run pytest` must pass. See `AGENTS.md` for agent rules.
"""

CHANGELOG_MD = """\
# Changelog
All notable changes to this project will be documented in this file.
"""

GITIGNORE_GIT = [".lsz/", ".pi/", ".agents/", "coverage/"]
GITIGNORE_PYTHON_EXTRA = ["__pycache__/", ".venv/"]
GITIGNORE_RUST_EXTRA = ["target/"]

PYTHON_VERSION = "3.14\n"


def build_pyproject(project_name: str, with_coverage: bool, threshold: int) -> str:
    cov_deps = ', "pytest-cov>=5"' if with_coverage else ""
    cov_section = ""
    if with_coverage:
        cov_section = f"""
[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.report]
show_missing = true
fail_under = {threshold}
"""
    return f"""[project]
name = "{project_name}"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = ["pytest>=8", "ruff>=0.11", "basedpyright>=1.30"{cov_deps}]

[tool.ruff]
line-length = 100
target-version = "py314"

[tool.basedpyright]
typeCheckingMode = "strict"

[tool.pytest.ini_options]
testpaths = ["tests"]
{cov_section}"""


PYPROJECT_TOML_TMPL = build_pyproject("{project_name}", False, 80)

RUST_TOOLCHAIN_TOML = """\
[toolchain]
channel = "stable"
components = ["rustfmt", "clippy"]
"""

CARGO_TOML_TMPL = """\
[package]
name = "{project_name}"
version = "0.1.0"
edition = "2021"

[dependencies]
"""

CI_PYTHON_VERIFY_YML = """\
name: Verify and Release
on:
  repository_dispatch:
    types: [semantic-release]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with: {fetch-depth: 0}
      - uses: astral-sh/setup-uv@v5
        with: {python-version: '3.14'}
      - run: uv sync --group dev
      - run: uv run ruff check .
      - run: uv run basedpyright
      - run: uv run pytest
  release:
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with: {fetch-depth: 0}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4  # zizmor: ignore[cache-poisoning]
        with: {node-version: 22}
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
"""

CI_PYTHON_COVERAGE_YML = """\
name: Verify and Release
on:
  repository_dispatch:
    types: [semantic-release]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with: {fetch-depth: 0}
      - uses: astral-sh/setup-uv@v5
        with: {python-version: '3.14'}
      - run: uv sync --group dev
      - run: uv run ruff check .
      - run: uv run basedpyright
      - run: uv run pytest --cov --cov-report=term-missing --cov-report=lcov --cov-fail-under=80
  release:
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with: {fetch-depth: 0}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4  # zizmor: ignore[cache-poisoning]
        with: {node-version: 22}
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
"""

CI_RUST_VERIFY_YML = """\
name: Verify and Release
on:
  repository_dispatch:
    types: [semantic-release]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with: {fetch-depth: 0}
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
      - run: cargo test
  release:
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with: {fetch-depth: 0}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4  # zizmor: ignore[cache-poisoning]
        with: {node-version: 22}
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
"""

CI_RUST_COVERAGE_YML = """\
name: Verify and Release
on:
  repository_dispatch:
    types: [semantic-release]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with: {fetch-depth: 0}
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo llvm-cov --workspace --lcov --output-path lcov.info
      - run: cargo llvm-cov report --fail-under-lines 80
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
  release:
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with: {fetch-depth: 0}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4  # zizmor: ignore[cache-poisoning]
        with: {node-version: 22}
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
"""


def infer_project_name(cwd: pathlib.Path) -> str:
    try:
        import subprocess

        out = (
            subprocess.check_output(
                ["git", "rev-parse", "--show-toplevel"], cwd=str(cwd), stderr=subprocess.DEVNULL
            )
            .decode()
            .strip()
        )
        if out:
            return pathlib.Path(out).name
    except Exception:
        pass
    return cwd.name


def write_file(
    path: pathlib.Path, content: str, dry_run: bool, *, warn_mixed: str | None = None
) -> bool:
    is_mixed = warn_mixed is not None
    if dry_run:
        if path.exists():
            old = path.read_text(encoding="utf-8")
            if old == content:
                print(f"unchanged  {path}", file=sys.stderr)
            else:
                diff = difflib.unified_diff(
                    old.splitlines(keepends=True),
                    content.splitlines(keepends=True),
                    fromfile=str(path),
                    tofile=str(path) + " (new)",
                )
                sys.stdout.writelines(diff)
        else:
            print(f"would create {path}:\n{content}", file=sys.stdout)
        if is_mixed:
            print(f"WARNING (dry-run): {path}: {warn_mixed}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    tag = "mixed" if is_mixed else "deterministic"
    print(f"wrote ({tag}) {path}", file=sys.stderr)
    if is_mixed:
        print(f"WARNING: {path}: {warn_mixed}", file=sys.stderr)
    return True


def append_gitignore(path: pathlib.Path, entries: list[str], dry_run: bool) -> None:
    if dry_run:
        existing: set[str] = set()
        if path.exists():
            existing = {
                ln.strip() for ln in path.read_text(encoding="utf-8").splitlines() if ln.strip()
            }
        missing = [e for e in entries if e not in existing]
        if missing:
            print(f"would append to {path}: {missing}", file=sys.stdout)
        else:
            print(f"unchanged  {path} (gitignore dedup)", file=sys.stderr)
        return
    existing_set: set[str] = set()
    if path.exists():
        text = path.read_text(encoding="utf-8")
        existing_set = {ln.strip() for ln in text.splitlines() if ln.strip()}
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
    missing = [e for e in entries if e not in existing_set]
    if not missing:
        print(f"unchanged  {path} (gitignore dedup)", file=sys.stderr)
        return
    with path.open("a", encoding="utf-8") as f:
        if path.exists() and path.stat().st_size > 0:
            content = path.read_text(encoding="utf-8")
            if not content.endswith("\n"):
                f.write("\n")
        for e in missing:
            f.write(e + "\n")
    print(f"appended ({len(missing)}) to {path}: {missing}", file=sys.stderr)


def patch_agents(path: pathlib.Path, snippet: str, dry_run: bool) -> None:
    marker = snippet.strip().splitlines()[0][:40]
    if dry_run:
        if path.exists():
            text = path.read_text(encoding="utf-8")
            if marker.strip("# ") in text or snippet.strip() in text:
                print(f"unchanged  {path} (AGENTS patch present)", file=sys.stderr)
            else:
                print(f"would patch {path} with:\n{snippet}", file=sys.stdout)
        else:
            print(f"would create {path} with:\n{snippet}", file=sys.stdout)
        print(
            f"WARNING (dry-run): {path}: proofread — keep existing 3 sections, verify pointer wording.",
            file=sys.stderr,
        )
        return
    if path.exists():
        text = path.read_text(encoding="utf-8")
        if snippet.strip() in text or marker.strip("# ") in text:
            print(f"unchanged  {path} (AGENTS patch present)", file=sys.stderr)
            print(
                f"WARNING: {path}: proofread — keep existing 3 sections, verify pointer wording.",
                file=sys.stderr,
            )
            return
        with path.open("a", encoding="utf-8") as f:
            if not text.endswith("\n"):
                f.write("\n")
            if not text.endswith("\n\n"):
                f.write("\n")
            f.write(snippet.rstrip() + "\n")
        print(f"patched {path} (mixed)", file=sys.stderr)
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(snippet.rstrip() + "\n", encoding="utf-8")
        print(f"wrote {path} (mixed)", file=sys.stderr)
    print(
        f"WARNING: {path}: proofread — keep existing 3 sections, verify pointer wording.",
        file=sys.stderr,
    )


def do_git(cwd: pathlib.Path, project_name: str, dry_run: bool) -> None:
    write_file(cwd / ".releaserc.json", RELEASERC_JSON, dry_run)
    write_file(cwd / ".github" / "workflows" / "release.yml", RELEASE_YML, dry_run)
    write_file(cwd / "commitlint.config.js", COMMITLINT_JS, dry_run)
    write_file(cwd / "CHANGELOG.md", CHANGELOG_MD, dry_run)
    contrib = CONTRIBUTING_MD_TMPL.format(project_name=project_name)
    write_file(
        cwd / "CONTRIBUTING.md",
        contrib,
        dry_run,
        warn_mixed="mixed: contains {{project_name}} + toolchain 'Before PR' line — proofread project name and lint/test commands.",
    )
    append_gitignore(cwd / ".gitignore", GITIGNORE_GIT, dry_run)
    patch_agents(
        cwd / "AGENTS.md",
        "### Contribution\nConventional commits & changelog: see CONTRIBUTING.md\n",
        dry_run,
    )


def do_python(
    cwd: pathlib.Path, project_name: str, dry_run: bool, with_coverage: bool, threshold: int
) -> None:
    write_file(cwd / ".python-version", PYTHON_VERSION, dry_run)
    pyproj = build_pyproject(project_name, with_coverage, threshold)
    warn = (
        f"mixed: {{{{project_name}}}} + coverage gate {threshold}% — proofread name and fail_under"
        if with_coverage
        else "mixed: {{project_name}} + description/readme — proofread package name and description."
    )
    write_file(
        cwd / "pyproject.toml",
        pyproj,
        dry_run,
        warn_mixed=warn,
    )
    append_gitignore(cwd / ".gitignore", GITIGNORE_GIT + GITIGNORE_PYTHON_EXTRA, dry_run)
    patch_agents(
        cwd / "AGENTS.md",
        "### Runtime\nPython: uv + .python-version (3.14), run via uv run; see pyproject.toml\n",
        dry_run,
    )
    contrib_py = CONTRIBUTING_MD_TMPL_PYTHON.format(project_name=project_name)
    write_file(
        cwd / "CONTRIBUTING.md",
        contrib_py,
        dry_run,
        warn_mixed="mixed: contains {{project_name}} + toolchain 'Before PR' line — proofread project name and lint/test commands.",
    )
    if with_coverage:
        print(
            f"NOTE: Python coverage wired — run `uv run pytest --cov --cov-fail-under={threshold}`",
            file=sys.stderr,
        )


def do_rust(
    cwd: pathlib.Path, project_name: str, dry_run: bool, with_coverage: bool, threshold: int
) -> None:
    cargo_name = project_name.lower().replace("_", "-").replace(" ", "-")
    if cargo_name != project_name:
        print(
            f"WARNING: Cargo package name normalized to '{cargo_name}' (from '{project_name}') — proofread Cargo.toml name.",
            file=sys.stderr,
        )
    write_file(cwd / "rust-toolchain.toml", RUST_TOOLCHAIN_TOML, dry_run)
    cargo = CARGO_TOML_TMPL.format(project_name=cargo_name)
    warn = "mixed: {{project_name}} normalized to kebab-case — proofread package name and edition."
    if with_coverage:
        warn += f" + coverage llvm-cov {threshold}%"
    write_file(
        cwd / "Cargo.toml",
        cargo,
        dry_run,
        warn_mixed=warn,
    )
    append_gitignore(cwd / ".gitignore", GITIGNORE_GIT + GITIGNORE_RUST_EXTRA, dry_run)
    patch_agents(
        cwd / "AGENTS.md",
        "### Runtime\nRust: cargo + rust-toolchain.toml (stable), verify via cargo fmt/clippy/test\n",
        dry_run,
    )
    if with_coverage:
        print(
            f"NOTE: Rust coverage requires `cargo llvm-cov` (install: cargo install cargo-llvm-cov). Threshold {threshold}% enforced via `cargo llvm-cov report --fail-under-lines {threshold}`",
            file=sys.stderr,
        )


def do_ci(
    cwd: pathlib.Path, dry_run: bool, variant: str, with_coverage: bool, threshold: int
) -> None:
    if variant == "python":
        if with_coverage:
            content = CI_PYTHON_COVERAGE_YML.replace(
                "--cov-fail-under=80", f"--cov-fail-under={threshold}"
            )
        else:
            content = CI_PYTHON_VERIFY_YML
    elif variant == "rust":
        if with_coverage:
            content = CI_RUST_COVERAGE_YML.replace(
                "--fail-under-lines 80", f"--fail-under-lines {threshold}"
            )
        else:
            content = CI_RUST_VERIFY_YML
    else:
        content = RELEASE_YML
        if with_coverage:
            print(
                "NOTE: Node coverage gate not auto-wired — add `c8 --check-coverage --lines 80` to verify job",
                file=sys.stderr,
            )
    write_file(cwd / ".github" / "workflows" / "release.yml", content, dry_run)


def main() -> int:
    ap = argparse.ArgumentParser(description="Deterministic scaffold generator")
    ap.add_argument(
        "--flavor",
        choices=["git", "python", "rust", "ci", "all"],
        required=True,
        help="flavor to scaffold",
    )
    ap.add_argument(
        "--project-name",
        default=None,
        help="project name for {{project_name}} (default: inferred from cwd)",
    )
    ap.add_argument("--dry-run", action="store_true", help="print diff without writing")
    ap.add_argument(
        "--ci-variant",
        choices=["node", "python", "rust"],
        default="node",
        help="CI verify variant (default: node)",
    )
    ap.add_argument("--cwd", default=".", help="target directory (default: .)")
    ap.add_argument(
        "--with-coverage",
        action="store_true",
        help="wire coverage gate (pytest-cov / cargo llvm-cov)",
    )
    ap.add_argument(
        "--coverage-threshold",
        type=int,
        default=80,
        help="coverage fail-under threshold (default: 80)",
    )

    args = ap.parse_args()

    cwd = pathlib.Path(args.cwd).resolve()
    project_name = args.project_name or infer_project_name(cwd)

    flavor: str = args.flavor
    dry_run: bool = args.dry_run
    with_coverage: bool = args.with_coverage
    threshold: int = args.coverage_threshold

    if threshold < 0 or threshold > 100:
        print("error: --coverage-threshold must be 0-100", file=sys.stderr)
        return 2

    if not project_name or not project_name.strip():
        print("error: --project-name is required when cwd has no inferrable name", file=sys.stderr)
        return 2

    if flavor in ("git", "all"):
        do_git(cwd, project_name, dry_run)
    if flavor in ("python", "all"):
        do_python(cwd, project_name, dry_run, with_coverage, threshold)
    if flavor in ("rust", "all"):
        do_rust(cwd, project_name, dry_run, with_coverage, threshold)
    if flavor == "ci":
        do_ci(cwd, dry_run, args.ci_variant, with_coverage, threshold)

    if dry_run:
        print(
            "dry-run complete — no files written (warnings on stderr are expected for mixed files)",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
